### ISSUE TITLE
how to Run program?

### ISSUE THREAD

**Issue by Sameeranjoshi** [Mrktn/ccg#1]
Hi, I didn't find any config file and how can I create an executable and use the command line options?

**Comment by Mrktn** [comment]
Hi there !
First, please build the program using the Makefile (you can tweak it a bit, first, so as to choose your favorite compiler for instance).
Then, the ccg executable will allow you to print a random C program to stdout, that you can then redirect to a file for compilation purposes. The --help flag will print command line options that you can use to control code generation.

Have fun !
