### ISSUE TITLE
ternary operators with an empty second parameter

### ISSUE THREAD

**Issue by monniaux** [Mrktn/ccg#6]
Ternary operators with an empty second parameter, e.g., `x ? : y`, are a gcc extension. Could it be possible to pass an option not to generate code that uses gcc-specific extensions? Thanks.

**Comment by Mrktn** [comment]
Hi @monniaux, it would definitely make sense to allow the user to disable gcc-only code, be it this example of empty parameter in ternary operators, or any other extension for that matter.

Myself I am not active in the development of ccg anymore, but if the feature would serve your purpose and if you find the time to implement it, I would very much welcome a PR!
